
import { Inter } from "next/font/google";
import "../main.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "cline side",
  description: "Generated by create next app",
};

export default function Userlayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>{children}</body>
    </html>
  );
}
