
import { Inter } from "next/font/google";
import "./login.scss";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "User Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
      <Header/>
      {children}
      <Footer/>
 
      </body>
    </html>
  );
}
